---
#"Description" : "Ansible Playbook to Configure a Secondary HDD & Apache

- name: Configure Secondary HDD & Configure Apache 
  hosts: localhost
  gather_facts: False
  tasks:
  become: true
  remote_user: ubuntu
  gather_facts: false
  tasks:    
    - name: partition new disk
      shell: /bin/echo -e "n\np\n1\n\n\nw" | sudo fdisk /dev/xvdb

    - filesystem:
        fstype: ext4
        dev: /dev/xvdb1
#        opts: -cc

    - name: Creates Apache Mount directory
      file: 
        path: /mnt/html 
        state: directory
        mode: "u=rwx,g=wx,o=rwx"

    - name: Mount New File System
      shell: sudo mount /dev/xvdb1 /mnt/html 

    - name: Make Mount Point Permanent
      shell: |
        echo '/dev/xvdb1    /mnt/html    ext4    defaults    0    1' >> /etc/fstab
      register: WelcomeApache

    - name: Creates Apache Root directory
      file: 
        path: /mnt/html/www 
        state: directory
        mode: "u=rwx,g=wx,o=rwx"

    - name: Write Welcome Page
      shell: |
        echo 'Hello AWS World' > /mnt/html/www/index.html
      register: WelcomeApache


#    - name: Transfer Apache Port Config  
#      copy:
#        src: ports.conf
#        dest: /etc/apache2/
#        owner: root
#        group: root
#        mode: 0777

#    - name: Transfer Apache New Default Doc Root  
#      copy:
#        src: 000-default.conf
#        dest: /etc/apache2/sites-available/
#        owner: root
#        group: root
#        mode: 0777

#    - name: Transfer Apache Default Root  
#      copy:
#        src: apache2.conf
#        dest: /etc/apache2/
#        owner: root
#        group: root
#        mode: 0777

#    - name: enabled mod_rewrite
#      apache2_module: name=rewrite state=present
#      notify:
#        - restart apache2
  
#  handlers:
#    - name: restart apache2
#      service: name=apache2 state=restarted   
